// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/seguimiento-card/Card.tsx": () => import("../components/mockups/seguimiento-card/Card.tsx")
};
